using SimpleModCheckerPlus.Systems.ModSettingsClasses;

namespace SimpleModCheckerPlus.Systems
{
    public class ModSettings
    {
        public string ModVersion { get; set; }
        public string LastUpdated { get; set; }
        public AdjustSchoolCapacitySettings AdjustSchoolCapacitySettings { get; set; }
        public AdjustTransitSettings AdjustTransitSettings { get; set; }
        public AdvancedLineToolSettings AdvancedLineToolSettings { get; set; }
        public AdvancedRoadNamingSettings AdvancedRoadNamingSettings { get; set; }
        public AdvancedSimulationSpeedSettings AdvancedSimulationSpeedSettings { get; set; }
        public AdvancedTPMSettings AdvancedTPMSettings { get; set; }
        public AllAboardSettings AllAboardSettings { get; set; }
        public AnarchySettings AnarchySettings { get; set; }
        public AreaBucketSettings AreaBucketSettings { get; set; }
        public AreaOfEffectSettings AreaOfEffectSettings { get; set; }
        public AssetIconCreatorSettings AssetIconCreatorSettings { get; set; }
        public AssetIconLibrarySettings AssetIconLibrarySettings { get; set; }
        public AssetMigrationUtilitySettings AssetMigrationUtilitySettings { get; set; }
        public AssetUIManagerSettings AssetUIManagerSettings { get; set; }
        public AssetVariationChangerSettings AssetVariationChangerSettings { get; set; }
        public AutoDistrictNameStationsSettings AutoDistrictNameStationsSettings { get; set; }
        public AutomaticBulldozeAndRepairSettings AutomaticBulldozeAndRepairSettings { get; set; }
        public AutoVehicleRenamerSettings AutoVehicleRenamerSettings { get; set; }
        public BetterBulldozerSettings BetterBulldozerSettings { get; set; }
        public BetterMoonLightSettings BetterMoonLightSettings { get; set; }
        public BetterTransitViewSettings BetterTransitViewSettings { get; set; }
        public BeyondNumbersSettings BeyondNumbersSettings { get; set; }
        public BoundaryLinesModifierSettings BoundaryLinesModifierSettings { get; set; }
        public BrushSizeUnlimiterSettings BrushSizeUnlimiterSettings { get; set; }
        public BuildingHeightAndFootprintSettings BuildingHeightAndFootprintSettings { get; set; }
        public BuildingUsageTrackerSettings BuildingUsageTrackerSettings { get; set; }
        public BuildingUseSettings BuildingUseSettings { get; set; }
        public CameraDragSettings CameraDragSettings { get; set; }
        public CameraFieldOfViewSettings CameraFieldOfViewSettings { get; set; }
        public CartoSettings CartoSettings { get; set; }
        public ChangeCompanySettings ChangeCompanySettings { get; set; }
        public ChirpGPTSettings ChirpGPTSettings { get; set; }
        public CimRouteHighlighterSettings CimRouteHighlighterSettings { get; set; }
        public CitizenCleanerSettings CitizenCleanerSettings { get; set; }
        public CitizenModelManagerSettings CitizenModelManagerSettings { get; set; }
        public CityControllerSettings CityControllerSettings { get; set; }
        public CityServiceCapacityAdjusterSettings CityServiceCapacityAdjusterSettings { get; set; }
        public CityStatsSettings CityStatsSettings { get; set; }
        public CityWatchdogSettings CityWatchdogSettings { get; set; }
        public CivicVoiceSettings CivicVoiceSettings { get; set; }
        public ClearanceHelperSettings ClearanceHelperSettings { get; set; }
        public CollisionBeGoneSettings CollisionBeGoneSettings { get; set; }
        public ColoredBikePathSettings ColoredBikePathSettings { get; set; }
        public ColoredBusLaneSettings ColoredBusLaneSettings { get; set; }
        public ConfigXMLSettings ConfigXMLSettings { get; set; }
        public CrimeRemoverSettings CrimeRemoverSettings { get; set; }
        public CustomChirpsSettings CustomChirpsSettings { get; set; }
        public CustomizableMenuSettings CustomizableMenuSettings { get; set; }
        public CustomRoadSnapSettings CustomRoadSnapSettings { get; set; }
        public CustomTourismSettings CustomTourismSettings { get; set; }
        public DCMilestoneRewardsSettings DCMilestoneRewardsSettings { get; set; }
        public DemandMasterControlSettings DemandMasterControlSettings { get; set; }
        public DetailedDescriptionsSettings DetailedDescriptionsSettings { get; set; }
        public DisableAccidentsSettings DisableAccidentsSettings { get; set; }
        public DisableHoverSettings DisableHoverSettings { get; set; }
        public DisablePlacementSwaySettings DisablePlacementSwaySettings { get; set; }
        public EasyZoningSettings EasyZoningSettings { get; set; }
        public EconomyEXSettings EconomyEXSettings { get; set; }
        public EmergencyGhostsSettings EmergencyGhostsSettings { get; set; }
        public EvenBetterSaveListSettings EvenBetterSaveListSettings { get; set; }
        public EventsControllerSettings EventsControllerSettings { get; set; }
        public EXRScreenshotSettings EXRScreenshotSettings { get; set; }
        public ExtendedRadioSettings ExtendedRadioSettings { get; set; }
        public ExtendedTooltipSettings ExtendedTooltipSettings { get; set; }
        public ExtraAssetsImporterSettings ExtraAssetsImporterSettings { get; set; }
        public ExtractorBoostSettings ExtractorBoostSettings { get; set; }
        public ExtractorsBegoneSettings ExtractorsBegoneSettings { get; set; }
        public FastBikesSettings FastBikesSettings { get; set; }
        public FastBoardingSettings FastBoardingSettings { get; set; }
        public FertilityControlSettings FertilityControlSettings { get; set; }
        public FindCharacterSettings FindCharacterSettings { get; set; }
        public FindItSettings FindItSettings { get; set; }
        public FireStarterSettings FireStarterSettings { get; set; }
        public FirstPersonCameraContinuedSettings FirstPersonCameraContinuedSettings { get; set; }
        public FiveTwentyNineTilesSettings FiveTwentyNineTilesSettings { get; set; }
        public FPSLimiterSettings FPSLimiterSettings { get; set; }
        public GhostwriterSettings GhostwriterSettings { get; set; }
        public GottaGoFastSettings GottaGoFastSettings { get; set; }
        public HallOfFameSettings HallOfFameSettings { get; set; }
        public HistoricalStartSettings HistoricalStartSettings { get; set; }
        public HoverColorsSettings HoverColorsSettings { get; set; }
        public I18NEverywhereSettings I18NEverywhereSettings { get; set; }
        public ImageOverlaySettings ImageOverlaySettings { get; set; }
        public InfoLoomTwoSettings InfoLoomTwoSettings { get; set; }
        public IntelligentCommoditySchedulingSettings IntelligentCommoditySchedulingSettings { get; set; }
        public LaClockSettings LaClockSettings { get; set; }
        public LodControlSettings LodControlSettings { get; set; }
        public LuminaSettings LuminaSettings { get; set; }
        public MagicGarbageSettings MagicGarbageSettings { get; set; }
        public MagicHearseSettings MagicHearseSettings { get; set; }
        public MagicMailSettings MagicMailSettings { get; set; }
        public MapExtSettings MapExtSettings { get; set; }
        public MapTextureReplacerSettings MapTextureReplacerSettings { get; set; }
        public MouseLightSettings MouseLightSettings { get; set; }
        public MoveItSettings MoveItSettings { get; set; }
        public NavigationViewSettings NavigationViewSettings { get; set; }
        public NetworkToolsSettings NetworkToolsSettings { get; set; }
        public NoDeadTreesSettings NoDeadTreesSettings { get; set; }
        public NodeControllerSettings NodeControllerSettings { get; set; }
        public NoPollutionSettings NoPollutionSettings { get; set; }
        public NoVehicleDespawnSettings NoVehicleDespawnSettings { get; set; }
        public NoVehicleTrailersSettings NoVehicleTrailersSettings { get; set; }
        public OSMExportSettings OSMExportSettings { get; set; }
        public OutsideTrafficAdjusterSettings OutsideTrafficAdjusterSettings { get; set; }
        public ParkingFeeControlSettings ParkingFeeControlSettings { get; set; }
        public ParkingMonitorSettings ParkingMonitorSettings { get; set; }
        public ParkingPricingSettings ParkingPricingSettings { get; set; }
        public PlatterSettings PlatterSettings { get; set; }
        public PlopTheGrowablesSettings PlopTheGrowablesSettings { get; set; }
        public PrefabAssetFixesSettings PrefabAssetFixesSettings { get; set; }
        public PublicWorksPlusSettings PublicWorksPlusSettings { get; set; }
        public RealisticIndustrialPowerConsumptionSettings RealisticIndustrialPowerConsumptionSettings { get; set; }
        public RealisticJobSearchSettings RealisticJobSearchSettings { get; set; }
        public RealisticParkingSettings RealisticParkingSettings { get; set; }
        public RealisticPathFindingSettings RealisticPathFindingSettings { get; set; }
        public RealisticTripsSettings RealisticTripsSettings { get; set; }
        public RealisticWorkplacesAndHouseholdsSettings RealisticWorkplacesAndHouseholdsSettings { get; set; }
        public RealLifeSettings RealLifeSettings { get; set; }
        public RecolorSettings RecolorSettings { get; set; }
        public RegionFlagIconsSettings RegionFlagIconsSettings { get; set; }
        public ResourceLocatorSettings ResourceLocatorSettings { get; set; }
        public RoadBuilderSettings RoadBuilderSettings { get; set; }
        public RoadConstructionEventsSettings RoadConstructionEventsSettings { get; set; }
        public RoadNameRemoverSettings RoadNameRemoverSettings { get; set; }
        public RoadPrecisionSettings RoadPrecisionSettings { get; set; }
        public RoadWearAdjusterSettings RoadWearAdjusterSettings { get; set; }
        public RoadWearToolToggleSettings RoadWearToolToggleSettings { get; set; }
        public SceneExplorerSettings SceneExplorerSettings { get; set; }
        public ServiceCimsSettings ServiceCimsSettings { get; set; }
        public ShowMoreHappinessSettings ShowMoreHappinessSettings { get; set; }
        public SimpleBrushSettings SimpleBrushSettings { get; set; }
        public SimpleModCheckerSettings SimpleModCheckerSettings { get; set; }
        public SimpleRadioSettings SimpleRadioSettings { get; set; }
        public SirenChangerSettings SirenChangerSettings { get; set; }
        public SmartTransportationSettings SmartTransportationSettings { get; set; }
        public SmartUpkeepManagerSettings SmartUpkeepManagerSettings { get; set; }
        public SnapToTopographySettings SnapToTopographySettings { get; set; }
        public SpeechFreeRadioSettings SpeechFreeRadioSettings { get; set; }
        public StationNamingSettings StationNamingSettings { get; set; }
        public SunGlassesSettings SunGlassesSettings { get; set; }
        public SuperFastBuildingAndLevelingSettings SuperFastBuildingAndLevelingSettings { get; set; }
        public TimeAndWeatherAnarchySettings TimeAndWeatherAnarchySettings { get; set; }
        public ToggleOverlaysSettings ToggleOverlaysSettings { get; set; }
        public TradingCostTweakerSettings TradingCostTweakerSettings { get; set; }
        public TrafficLightManagerSettings TrafficLightManagerSettings { get; set; }
        public TrafficLightsEnhancementSettings TrafficLightsEnhancementSettings { get; set; }
        public TrafficSettings TrafficSettings { get; set; }
        public TrafficSettingsSettings TrafficSettingsSettings { get; set; }
        public TrafficSpySettings TrafficSpySettings { get; set; }
        public TrafficToolEssentialsSettings TrafficToolEssentialsSettings { get; set; }
        public TransitNightSchedulerSettings TransitNightSchedulerSettings { get; set; }
        public TransportPolicyAdjusterSettings TransportPolicyAdjusterSettings { get; set; }
        public TreeControllerSettings TreeControllerSettings { get; set; }
        public TreesReduceNoisePollutionSettings TreesReduceNoisePollutionSettings { get; set; }
        public TripsViewSettings TripsViewSettings { get; set; }
        public UrbanInequalitySettings UrbanInequalitySettings { get; set; }
        public VehicleControllerSettings VehicleControllerSettings { get; set; }
        public VehicleVariationPacksSettings VehicleVariationPacksSettings { get; set; }
        public WaterFeaturesSettings WaterFeaturesSettings { get; set; }
        public WaterVisualTweaksSettings WaterVisualTweaksSettings { get; set; }
        public WetRoadsSettings WetRoadsSettings { get; set; }
        public WriteEverywhereSettings WriteEverywhereSettings { get; set; }
        public ZoneColorChangerSettings ZoneColorChangerSettings { get; set; }
        public ZoneToolsSettings ZoneToolsSettings { get; set; }
    }
}
