using System.Collections.Generic;

internal static class ModSettingsMap
{
    private static readonly HashSet<string> ValidKeys = new()
    {
        "74285+SceneExplorer.Settings",
        "74286+FPS_Limiter.FPSLimiterSettings",
        "74324+MoveIt.Settings.Settings",
        "74328+FiveTwentyNineTiles.ModSettings",
        "74535+HistoricalStart.ModSettings",
        "74539+ImageOverlay.ModSettings",
        "74604+Anarchy.Settings.AnarchyModSettings",
        "75249+BrushSizeUnlimiter.MyOptions",
        "75250+Better_Bulldozer.Settings.BetterBulldozerModSettings",
        "75426+I18NEverywhere.Setting",
        "75613+Water_Features.Settings.WaterFeaturesSettings",
        "75816+LineTool.ModSettings",
        "75826+PlopTheGrowables.ModSettings",
        "75862+ExtendedRadio.Setting",
        "75993+Tree_Controller.Settings.TreeControllerSettings",
        "76050+MapTextureReplacer.MapTextureReplacerOptions",
        "76662+EmploymentTracker.EmploymentTrackerSettings",
        "76849+SunGlasses.Setting",
        "76908+AutoDistrictNameStations.ModOptions",
        "76972+CrimeRemover.Setting.CrimeSetting",
        "77171+Time2Work.Setting",
        "77240+FindIt.FindItSettings",
        "77260+WaterVisualTweaksMod.WaterVisualTweaksSettings",
        "77321+SuperFastBuildingAndLeveling.Setting",
        "77345+FireStarter.Setting",
        "77463+RoadNameRemover.Setting",
        "77923+BetterMoonLight.Setting",
        "78131+StationNaming.Setting.StationNamingSettings",
        "78188+ExtendedTooltip.ModSettings",
        "78601+NoPollution.Setting",
        "78622+TransportPolicyAdjuster.Setting",
        "78847+AssetVariationChanger.Setting",
        "79186+SimpleModCheckerPlus.Setting",
        "79237+FirstPersonCameraContinued.Setting",
        "79634+AssetIconLibrary.Setting",
        "79872+AutoVehicleRenamer.Setting",
        "80095+Traffic.ModSettings",
        "80529+ExtraAssetsImporter.Setting",
        "80931+ToggleableOverlays.Setting",
        "81012+VehicleVariationPacks.Setting",
        "81157+AreaBucket.Setting",
        "81568+ZoneColorChanger.Setting",
        "82675+DCMilestoneRewards.Setting",
        "84638+Recolor.Settings.Setting",
        "85211+NoTrafficDespawn.TrafficDespawnSettings",
        "85284+CityStats.ModSettings",
        "86124+TradingCostTweaker.Setting",
        "86553+NoVehicleTrailers.Setting",
        "86605+AllAboard.Setting",
        "86728+BoundaryLinesModifier.Setting",
        "86868+RealLife.Setting",
        "86944+DemandMasterControl.Setting",
        "87190+RoadBuilder.Setting",
        "87313+RealisticParking.Setting",
        "87422+OSMExport.Setting",
        "87428+Carto.Settings",
        "87755+RealisticWorkplacesAndHouseholds.Setting",
        "88500+NoDeadTrees.NoDeadTreesSetting",
        "88893+TimeWeatherAnarchy.TimeWeatherAnarchySettings ",
        "90264+SmartTransportation.Setting",
        "90641+HallOfFame.Settings",
        "91433+InfoLoomTwo.Setting",
        "92908+BelzontWE.WEModData",
        "92952+CitizenModelManager.Setting",
        "94394+Lumina.Setting",
        "94762+BuildingUse.ModSettings",
        "95437+RegionFlagIcons.Setting",
        "95872+CameraFieldOfView.Setting",
        "96619+TripsDataView.Setting",
        "96718+RoadWearAdjuster.Setting",
        "97195+ParkingMonitor.Setting",
        "97381+CityServiceCapacityAdjuster.Setting",
        "98560+AssetUIManager.Setting",
        "98771+SpeechFreeRadio.ModSettings.ModSettings",
        "99048+ResourceLocator.ModSettings",
        "103983+ShowMoreHappiness.ModSettings",
        "104707+DetailedDescriptions.Setting",
        "104781+VehicleController.Setting",
        "105288+AssetIconCreator.Setting",
        "105715+DisableAccidents.ModSettings.Setting",
        "105800+EventsController.Settings.Setting",
        "107487+SmartUpkeepManager.Setting",
        "107939+MapExtPDX.ModSettings",
        "110245+UrbanInequality.Setting",
        "112452+ParkingPricing.ModSettings",
        "112978+EvenBetterSaveList.Setting",
        "113193+BuildingUsageTracker.Setting",
        "113708+PrefabAssetFixes.Setting",
        "116595+CustomizableMenu.Setting",
        "117161+CitizenCleaner.Setting",
        "120143+crud89.ExtractorsBegone.ModSettings",
        "121226+RealisticPathFinding.Setting",
        "121812+CustomChirps.Setting",
        "122865+RoadWearToolToggle.RoadWearToolToggleSetting",
        "123345+FindIt.Character.Setting",
        "123497+MagicHearse.MHSetting",
        "123500+RealisticJobSearch.Setting",
        "123738+AdjustTransit.Setting",
        "123887+AdjustSchoolCapacity.ASCSetting",
        "124159+MagicGarbage.Setting",
        "124304+AdvancedSimulationSpeed.Setting",
        "124548+GottaGoFast.Setting",
        "124553+LaClock.ModSettings",
        "124947+OutsideTrafficAdjuster.Setting",
        "125278+Platter.Settings.PlatterModSettings",
        "125342+C2VM.TrafficToolEssentials.Settings",
        "125343+MagicMail.Setting",
        "125675+ConfigXML.Setting",
        "126306+Red_bike_path.Setting",
        "126355+Road_Precision.Setting",
        "126468+Colored_Bus_Lane.Setting",
        "127507+AssetMigrationUtility.Setting",
        "128269+ZoningToolkit.Setting",
        "128566+TrafficSpy.ModSettings.ModSettings",
        "128577+BuildingHeightAndFootprint.ModSettings",
        "128911+C2VM.TrafficLightsEnhancement.Settings",
        "129323+CollisionBeGone.Setting",
        "130383+Realistic_Industrial_Power_Consumption.Setting",
        "131525+EmergencyGhosts.Setting",
        "132866+CS2_Clearance.Setting",
        "133261+ServiceCims.ModSettings",
        "133736+NetworkTools.Settings.NT_Settings",
        "134032+ParkingFeeControl.ModSettings",
        "134067+BikesAndPaths.BPSetting",
        "135367+SirenChanger.SirenChangerSettings",
        "136261+EasyZoning.Setting",
        "136370+ChirpGPT.Setting",
        "137149+EconomyEX.Settings.ModSettings",
        "137401+ExtractorBoost.Setting",
        "138174+MertsToolBox.Settings.ToolBoxSettings",
        "138390+PublicWorksPlus.ATTSettings",
        "138523+NodeController.Setting",
        "139487+TrafficLightManager.Code.Settings",
        "139584+CameraDrag.Setting",
        "139595+BetterTransitView.ModSettings.ModSettings",
        "139839+EXRScreenshot.Settings.Setting",
        "140062+Traffic_Settings.Setting",
        "140676+Taskly.Setting",
        "141243+CustomizeIt.Setting",
        "141486+AdvancedTPM.TPMModSettings",
        "141603+DisableHover.Settings.ModSettings",
        "141606+CustomRoadSnap.Setting",
        "141751+LodControl.Setting",
        "141997+FastBoarding.Setting",
        "142309+Beyond_Numbers_with_STT.Setting",
        "142520+RoadConstructionEvents.Setting",
        "142766+AutomaticBulldozeAndRepair.Setting",
        "143447+WetRoads.Setting",
        "143732+TreesReduceNoisePollution.Setting",
        "143857+FertilityControl.Setting",
        "144000+SnapToTopography.Setting",
        "144130+HardMode.Settings.HardModeSettings",
        "144908+CityWatchdog.CwdSettings",
        "145021+Area_of_Effect.ModSettings.ModSettings",
        "145221+AdvancedRoadNaming.Settings.AdvancedRoadNamingSettings",
        "145605+CityStoryMod.Settings",
        "145663+SimpleRadio.Settings.ModSettings",
        "145932+SimpleBrush.Settings.ModSettings",
        "146044+HoverColors.Settings.HoverColorsSettings",
        "146160+DisablePlacementSway.Setting",
        "146643+CS2_Metro.Setting",
        "146817+IntelligentCommodityScheduling.ICSSettings",
        "146902+Pinboard.Setting",
        "147311+CivicVoice.CivicVoiceSettings",
        "147521+MouseLight.MouseLightSettings",
        "147630+NightVehiclesMod.ModSettings",
        "147696+PriceAdjuster.Settings.PriceSettings",
        "147967+ShowInvisibleNetworks.Setting",
        "148141+GrassSprites.Setting",
        "148221+AssetDisabler.Setting",
        "148616+AssetMenuTweaks.Setting",
        "148861+ToggleEdgeScrolling.Setting",
        "148865+CitySounds.Setting",
        "148970+MeshStatsViewer.Setting",
        "149883+RapidTransitMod.Settings.AtoGameOptions",
        "149918+BetterEducationInfoView.Setting",
        "149990+RoadRailSpeeds.SpeedLimitsSetting",
        "150138+CustomLandParcel.CustomLandParcelSettings",
        "150540+EmergencyPriority.EmergencyPrioritySetting",
        "150546+TransitTimetables.TransitTimetablesSetting",
        "150547+WholesaleLogistics.WholesaleLogisticsSetting",
        "150664+StopJaywalking.StopJaywalkingSetting",
        "150863+TownRoadLane.TownRoadLaneSetting",
        "151219+PaulovRentMod.Setting",
        "151254+PaulovUKEconomy.ModSetting",
        "151387+WelfareManagement.WelfareManagementSetting",
        "151388+ServiceSanitationLevy.ServiceSanitationLevySetting",
        "151389+PrivateSchoolsHospitals.PrivateSchoolsHospitalsSetting",
        "151415+AutoBulldozer.Setting",
        "151484+BuildingReviver.Setting",
        "151615+CemeteryOverflowManager.Setting",
        "151632+PrisonOverflowManager.Setting",
        "151745+GridRoadGenerator.Settings.GridRoadGeneratorSettings",
        "151747+SignatureFix.SignatureFixSettings",
        "151881+RemoveAbandonedCars.Settings.Setting",
        "151943+NaturalRegrowth.Setting",
        "152071+Skyplan.Setting",
        "152153+ConcurrentBusBoarding.ConcurrentBusBoardingSettings",
        "152275+PlopShuffle.PlopShuffleSettings",
        "152354+DistrictHeightPolicy.Setting",
        "152722+RoadNameGenerator.Setting",
        "152742+RealisticTimeAndTraffic.Setting",
        "153071+RoundaboutMarker.RoundaboutMarkerSettings",
        "153543+TourismOverhaul.TourismOverhaulSetting",
        "153684+AreaBulldozer.Setting",
        "154015+Kobbyist.ProgressionControls.KobbyistProgressionControlsSettings",
        "154120+Planboard.Settings",
        "154183+RealWeatherSync.Settings.RealWeatherSettings",
        "154291+CSII_Realistic_Alignment.Setting",
        "154371+Copaste.CopasteSettings",
        "154658+DistrictGroups.Setting",
        "155637+NoSpeedLimitMarkings.Setting",
        "155806+ParkingControl.PCSettings",
        "155839+RouteFilter.Setting",
        "156092+ScorchedEarth.ScorchedEarthSettings",
        "156593+CrashRepair.Setting",
        "156605+DedicatedCargoFacilities.Setting",
        "157162+HistoricalTool.Setting",
        "157334+RoadRule.Settings",
        "157424+BitulaMod.Setting",
        "157660+TaxiTraffic.TaxiSettings",
        "157700+Seety.Settings.SeetySettings",
        "157711+BulldozerMarquee.Settings",
        "157738+DimThatHighlight.Settings",
        "157802+Cs2AutoTranslator.TranslatorSetting",
        "157843+SkylinesMaps.ModSettings",
        "157965+RailwaySignals.Setting",
        "158089+AutoNighttimeLightExtension.Setting",
        "158167+CityMonitor.Setting",
        "158284+FirstMapPopup.PopupSettings",
    };

    private static readonly Dictionary<string, string> ClassNames = new()
    {
        ["SceneExplorer.Settings+SceneExplorer"] = "SceneExplorerSettings",
        ["FPS_Limiter.FPSLimiterSettings+FPS_Limiter"] = "FPSLimiterSettings",
        ["MoveIt.Settings.Settings+MoveIt"] = "MoveItSettings",
        ["FiveTwentyNineTiles.ModSettings+FiveTwentyNineTiles"] = "FiveTwentyNineTilesSettings",
        ["HistoricalStart.ModSettings+HistoricalStart"] = "HistoricalStartSettings",
        ["ImageOverlay.ModSettings+ImageOverlay"] = "ImageOverlaySettings",
        ["Anarchy.Settings.AnarchyModSettings+Anarchy"] = "AnarchySettings",
        ["BrushSizeUnlimiter.MyOptions+BrushSizeUnlimiter"] = "BrushSizeUnlimiterSettings",
        ["Better_Bulldozer.Settings.BetterBulldozerModSettings+BetterBulldozer"] =
            "BetterBulldozerSettings",
        ["I18NEverywhere.Setting+I18NEverywhere"] = "I18NEverywhereSettings",
        ["Water_Features.Settings.WaterFeaturesSettings+Water_Features"] = "WaterFeaturesSettings",
        ["LineTool.ModSettings+LineTool"] = "AdvancedLineToolSettings",
        ["PlopTheGrowables.ModSettings+PlopTheGrowables"] = "PlopTheGrowablesSettings",
        ["ExtendedRadio.Setting+ExtendedRadio"] = "ExtendedRadioSettings",
        ["Tree_Controller.Settings.TreeControllerSettings+Tree_Controller"] =
            "TreeControllerSettings",
        ["MapTextureReplacer.MapTextureReplacerOptions+MapTextureReplacer"] =
            "MapTextureReplacerSettings",
        ["EmploymentTracker.EmploymentTrackerSettings+EmploymentTracker"] =
            "CimRouteHighlighterSettings",
        ["SunGlasses.Setting+SunGlasses"] = "SunGlassesSettings",
        ["AutoDistrictNameStations.ModOptions+AutoDistrictNameStations"] =
            "AutoDistrictNameStationsSettings",
        ["CrimeRemover.Setting.CrimeSetting+CrimeRemover"] = "CrimeRemoverSettings",
        ["Time2Work.Setting+Time2Work"] = "RealisticTripsSettings",
        ["FindIt.FindItSettings+FindIt"] = "FindItSettings",
        ["WaterVisualTweaksMod.WaterVisualTweaksSettings+WaterVisualTweaks"] =
            "WaterVisualTweaksSettings",
        ["SuperFastBuildingAndLeveling.Setting+SuperFastBuildingAndLeveling"] =
            "SuperFastBuildingAndLevelingSettings",
        ["FireStarter.Setting+FireStarter"] = "FireStarterSettings",
        ["RoadNameRemover.Setting+RoadNameRemover"] = "RoadNameRemoverSettings",
        ["BetterMoonLight.Setting+BetterMoonLight"] = "BetterMoonLightSettings",
        ["StationNaming.Setting.StationNamingSettings+StationNaming"] = "StationNamingSettings",
        ["ExtendedTooltip.ModSettings+ExtendedTooltip"] = "ExtendedTooltipSettings",
        ["NoPollution.Setting+NoPollution"] = "NoPollutionSettings",
        ["TransportPolicyAdjuster.Setting+TransportPolicyAdjuster"] =
            "TransportPolicyAdjusterSettings",
        ["AssetVariationChanger.Setting+AssetVariationChanger"] = "AssetVariationChangerSettings",
        ["SimpleModCheckerPlus.Setting+SimpleModCheckerPlus"] = "SimpleModCheckerSettings",
        ["FirstPersonCameraContinued.Setting+FirstPersonCameraContinued"] =
            "FirstPersonCameraContinuedSettings",
        ["AssetIconLibrary.Setting+AssetIconLibrary"] = "AssetIconLibrarySettings",
        ["AutoVehicleRenamer.Setting+AutoVehicleRenamer"] = "AutoVehicleRenamerSettings",
        ["Traffic.ModSettings+Traffic"] = "TrafficSettings",
        ["ExtraAssetsImporter.Setting+ExtraAssetsImporter"] = "ExtraAssetsImporterSettings",
        ["ToggleableOverlays.Setting+ToggleableOverlays"] = "ToggleOverlaysSettings",
        ["VehicleVariationPacks.Setting+VehicleVariationPacks"] = "VehicleVariationPacksSettings",
        ["AreaBucket.Setting+AreaBucket"] = "AreaBucketSettings",
        ["ZoneColorChanger.Setting+ZoneColorChanger"] = "ZoneColorChangerSettings",
        ["DCMilestoneRewards.Setting+DCMilestoneRewards"] = "DCMilestoneRewardsSettings",
        ["Recolor.Settings.Setting+Recolor"] = "RecolorSettings",
        ["NoTrafficDespawn.TrafficDespawnSettings+NoTrafficDespawn"] = "NoVehicleDespawnSettings",
        ["CityStats.ModSettings+CityStats"] = "CityStatsSettings",
        ["TradingCostTweaker.Setting+TradingCostTweaker"] = "TradingCostTweakerSettings",
        ["NoVehicleTrailers.Setting+NoVehicleTrailers"] = "NoVehicleTrailersSettings",
        ["AllAboard.Setting+AllAboard"] = "AllAboardSettings",
        ["BoundaryLinesModifier.Setting+BoundaryLinesModifier"] = "BoundaryLinesModifierSettings",
        ["RealLife.Setting+RealLife"] = "RealLifeSettings",
        ["DemandMasterControl.Setting+DemandMasterControl"] = "DemandMasterControlSettings",
        ["RoadBuilder.Setting+RoadBuilder"] = "RoadBuilderSettings",
        ["RealisticParking.Setting+RealisticParking"] = "RealisticParkingSettings",
        ["OSMExport.Setting+OSMExport"] = "OSMExportSettings",
        ["Carto.Settings+Carto"] = "CartoSettings",
        ["RealisticWorkplacesAndHouseholds.Setting+RWH"] =
            "RealisticWorkplacesAndHouseholdsSettings",
        ["NoDeadTrees.NoDeadTreesSetting+NoDeadTrees"] = "NoDeadTreesSettings",
        ["TimeWeatherAnarchy.TimeWeatherAnarchySettings +TimeWeatherAnarchy"] =
            "TimeAndWeatherAnarchySettings",
        ["SmartTransportation.Setting+SmartTransportation"] = "SmartTransportationSettings",
        ["HallOfFame.Settings+HallOfFame"] = "HallOfFameSettings",
        ["InfoLoomTwo.Setting+InfoLoomTwo"] = "InfoLoomTwoSettings",
        ["BelzontWE.WEModData+BelzontWE"] = "WriteEverywhereSettings",
        ["CitizenModelManager.Setting+CitizenModelManager"] = "CitizenModelManagerSettings",
        ["Lumina.Setting+Lumina"] = "LuminaSettings",
        ["BuildingUse.ModSettings+BuildingUse"] = "BuildingUseSettings",
        ["RegionFlagIcons.Setting+RegionFlagIcons"] = "RegionFlagIconsSettings",
        ["CameraFieldOfView.Setting+CameraFieldOfView"] = "CameraFieldOfViewSettings",
        ["TripsDataView.Setting+TripsDataView"] = "TripsViewSettings",
        ["RoadWearAdjuster.Setting+RoadWearAdjuster"] = "RoadWearAdjusterSettings",
        ["ParkingMonitor.Setting+ParkingMonitor"] = "ParkingMonitorSettings",
        ["CityServiceCapacityAdjuster.Setting+CityServiceCapacityAdjuster"] =
            "CityServiceCapacityAdjusterSettings",
        ["AssetUIManager.Setting+AssetUIManager"] = "AssetUIManagerSettings",
        ["SpeechFreeRadio.ModSettings.ModSettings+SpeechFreeRadio"] = "SpeechFreeRadioSettings",
        ["ResourceLocator.ModSettings+ResourceLocator"] = "ResourceLocatorSettings",
        ["ShowMoreHappiness.ModSettings+ShowMoreHappiness"] = "ShowMoreHappinessSettings",
        ["DetailedDescriptions.Setting+DetailedDescriptions"] = "DetailedDescriptionsSettings",
        ["VehicleController.Setting+VehicleController"] = "VehicleControllerSettings",
        ["AssetIconCreator.Setting+AssetIconCreator"] = "AssetIconCreatorSettings",
        ["DisableAccidents.ModSettings.Setting+DisableAccidents"] = "DisableAccidentsSettings",
        ["EventsController.Settings.Setting+EventsController"] = "EventsControllerSettings",
        ["SmartUpkeepManager.Setting+SmartUpkeepManager"] = "SmartUpkeepManagerSettings",
        ["MapExtPDX.ModSettings+MapExt2"] = "MapExtSettings",
        ["UrbanInequality.Setting+UrbanInequality"] = "UrbanInequalitySettings",
        ["ParkingPricing.ModSettings+ParkingPricing"] = "ParkingPricingSettings",
        ["EvenBetterSaveList.Setting+EvenBetterSaveList"] = "EvenBetterSaveListSettings",
        ["BuildingUsageTracker.Setting+BuildingUsageTracker"] = "BuildingUsageTrackerSettings",
        ["PrefabAssetFixes.Setting+PrefabAssetFixes"] = "PrefabAssetFixesSettings",
        ["CustomizableMenu.Setting+CustomizableMenu"] = "CustomizableMenuSettings",
        ["CitizenCleaner.Setting+CitizenCleaner"] = "CitizenCleanerSettings",
        ["crud89.ExtractorsBegone.ModSettings+ExtractorsBegone"] = "ExtractorsBegoneSettings",
        ["RealisticPathFinding.Setting+RealisticPathFinding"] = "RealisticPathFindingSettings",
        ["CustomChirps.Setting+CustomChirps"] = "CustomChirpsSettings",
        ["RoadWearToolToggle.RoadWearToolToggleSetting+RoadWearToolToggle"] =
            "RoadWearToolToggleSettings",
        ["FindIt.Character.Setting+FindIt.Character"] = "FindCharacterSettings",
        ["MagicHearse.MHSetting+MagicHearse"] = "MagicHearseSettings",
        ["RealisticJobSearch.Setting+RealisticJobSearch"] = "RealisticJobSearchSettings",
        ["AdjustTransit.Setting+AdjustTransit"] = "AdjustTransitSettings",
        ["AdjustSchoolCapacity.ASCSetting+AdjustSchoolCapacity"] = "AdjustSchoolCapacitySettings",
        ["MagicGarbage.Setting+MagicGarbage"] = "MagicGarbageSettings",
        ["AdvancedSimulationSpeed.Setting+AdvancedSimulationSpeed"] =
            "AdvancedSimulationSpeedSettings",
        ["GottaGoFast.Setting+GottaGoFast"] = "GottaGoFastSettings",
        ["LaClock.ModSettings+LaClock"] = "LaClockSettings",
        ["OutsideTrafficAdjuster.Setting+OutsideTrafficAdjuster"] =
            "OutsideTrafficAdjusterSettings",
        ["Platter.Settings.PlatterModSettings+Platter"] = "PlatterSettings",
        ["C2VM.TrafficToolEssentials.Settings+C2VM.TrafficToolEssentials"] =
            "TrafficToolEssentialsSettings",
        ["MagicMail.Setting+MagicMail"] = "MagicMailSettings",
        ["ConfigXML.Setting+ConfigXML"] = "ConfigXMLSettings",
        ["Red_bike_path.Setting+Red_bike_path"] = "ColoredBikePathSettings",
        ["Road_Precision.Setting+Road_Precision"] = "RoadPrecisionSettings",
        ["Colored_Bus_Lane.Setting+Colored_Bus_Lane"] = "ColoredBusLaneSettings",
        ["AssetMigrationUtility.Setting+AssetMigrationUtility"] = "AssetMigrationUtilitySettings",
        ["ZoningToolkit.Setting+ZoningToolkit"] = "ZoneToolsSettings",
        ["TrafficSpy.ModSettings.ModSettings+TrafficSpy"] = "TrafficSpySettings",
        ["BuildingHeightAndFootprint.ModSettings+BuildingHeightAndFootprint"] =
            "BuildingHeightAndFootprintSettings",
        ["C2VM.TrafficLightsEnhancement.Settings+C2VM.TrafficLightsEnhancement"] =
            "TrafficLightsEnhancementSettings",
        ["CollisionBeGone.Setting+CollisionBeGone"] = "CollisionBeGoneSettings",
        ["Realistic_Industrial_Power_Consumption.Setting+Realistic_Industrial_Power_Consumption"] =
            "RealisticIndustrialPowerConsumptionSettings",
        ["EmergencyGhosts.Setting+EmergencyGhosts"] = "EmergencyGhostsSettings",
        ["CS2_Clearance.Setting+CS2_Clearance"] = "ClearanceHelperSettings",
        ["ServiceCims.ModSettings+ServiceCims"] = "ServiceCimsSettings",
        ["NetworkTools.Settings.NT_Settings+NetworkTools"] = "NetworkToolsSettings",
        ["ParkingFeeControl.ModSettings+ParkingFeeControl"] = "ParkingFeeControlSettings",
        ["BikesAndPaths.BPSetting+BikesAndPaths"] = "BikesPlusPathsSettings",
        ["SirenChanger.SirenChangerSettings+SirenChanger"] = "SirenChangerSettings",
        ["EasyZoning.Setting+EasyZoning"] = "EasyZoningSettings",
        ["ChirpGPT.Setting+ChirpGPT"] = "ChirpGPTSettings",
        ["EconomyEX.Settings.ModSettings+EconomyEX"] = "EconomyEXSettings",
        ["ExtractorBoost.Setting+ExtractorBoost"] = "ExtractorBoostSettings",
        ["MertsToolBox.Settings.ToolBoxSettings+MertsToolBox"] = "MertsToolBoxSettings",
        ["PublicWorksPlus.ATTSettings+PublicWorksPlus"] = "AllTransitPlusTrucksSettings",
        ["NodeController.Setting+NodeController"] = "NodeControllerSettings",
        ["TrafficLightManager.Code.Settings+TrafficLightManager.Code"] =
            "TrafficLightManagerSettings",
        ["CameraDrag.Setting+CameraDrag"] = "CameraDragSettings",
        ["BetterTransitView.ModSettings.ModSettings+BetterTransitView"] =
            "BetterTransitViewSettings",
        ["EXRScreenshot.Settings.Setting+EXRScreenshot"] = "EXRScreenshotSettings",
        ["Traffic_Settings.Setting+Traffic_Settings"] = "TrafficSettingsSettings",
        ["Taskly.Setting+Taskly"] = "TasklySettings",
        ["CustomizeIt.Setting+CustomizeIt"] = "CustomTourismSettings",
        ["AdvancedTPM.TPMModSettings+AdvancedTPM"] = "AdvancedTPMSettings",
        ["DisableHover.Settings.ModSettings+DisableHover"] = "DisableHoverSettings",
        ["CustomRoadSnap.Setting+CustomRoadSnap"] = "CustomRoadSnapSettings",
        ["LodControl.Setting+LodControl"] = "LodControlSettings",
        ["FastBoarding.Setting+FastBoarding"] = "FastBoardingSettings",
        ["Beyond_Numbers_with_STT.Setting+Beyond_Numbers_with_STT"] = "BeyondNumbersSettings",
        ["RoadConstructionEvents.Setting+RoadConstructionEvents"] =
            "RoadConstructionEventsSettings",
        ["AutomaticBulldozeAndRepair.Setting+AutomaticBulldozeAndRepair"] =
            "AutomaticBulldozeAndRepairSettings",
        ["WetRoads.Setting+WetRoads"] = "WetRoadsSettings",
        ["TreesReduceNoisePollution.Setting+TreesReduceNoisePollution"] =
            "TreesReduceNoisePollutionSettings",
        ["FertilityControl.Setting+FertilityControl"] = "FertilityControlSettings",
        ["SnapToTopography.Setting+SnapToTopography"] = "SnapToTopographySettings",
        ["HardMode.Settings.HardModeSettings+HardMode"] = "HardModeContinuedSettings",
        ["CityWatchdog.CwdSettings+CityWatchdog"] = "CityWatchdogSettings",
        ["Area_of_Effect.ModSettings.ModSettings+Area_of_Effect"] = "AreaOfEffectSettings",
        ["AdvancedRoadNaming.Settings.AdvancedRoadNamingSettings+AdvancedRoadNaming"] =
            "AdvancedRoadNamingSettings",
        ["CityStoryMod.Settings+CityStoryMod"] = "GhostwriterSettings",
        ["SimpleRadio.Settings.ModSettings+SimpleRadio"] = "SimpleRadioSettings",
        ["SimpleBrush.Settings.ModSettings+SimpleBrush"] = "SimpleBrushSettings",
        ["HoverColors.Settings.HoverColorsSettings+HoverColors"] = "HoverColorsSettings",
        ["DisablePlacementSway.Setting+DisablePlacementSway"] = "DisablePlacementSwaySettings",
        ["CS2_Metro.Setting+CS2_Metro"] = "MetroDiagramSettings",
        ["IntelligentCommodityScheduling.ICSSettings+IntelligentCommodityScheduling"] =
            "IntelligentCommoditySchedulingSettings",
        ["Pinboard.Setting+Pinboard"] = "PinboardSettings",
        ["CivicVoice.CivicVoiceSettings+CivicVoice"] = "CivicVoiceSettings",
        ["MouseLight.MouseLightSettings+MouseLight"] = "MouseLightSettings",
        ["NightVehiclesMod.ModSettings+NightVehiclesMod"] = "TransitNightSchedulerSettings",
        ["PriceAdjuster.Settings.PriceSettings+PriceAdjuster"] = "PriceAdjusterSettings",
        ["ShowInvisibleNetworks.Setting+ShowInvisibleNetworks"] = "ShowInvisibleNetworksSettings",
        ["GrassSprites.Setting+ GrassSprites"] = "GrassSpritesSettings",
        ["AssetDisabler.Setting+AssetDisabler"] = "AssetDisablerSettings",
        ["AssetMenuTweaks.Setting+AssetMenuTweaks"] = "AssetMenuTweaksSettings",
        ["ToggleEdgeScrolling.Setting+ToggleEdgeScrolling"] = "ToggleEdgeScrollingSettings",
        ["CitySounds.Setting+CitySounds"] = "CitySoundsSettings",
        ["MeshStatsViewer.Setting+MeshStatsViewer"] = "MeshStatsViewerSettings",
        ["RapidTransitMod.Settings.AtoGameOptions+RapidTransitMod"] =
            "AdvancedTransitOperationsSettings",
        ["BetterEducationInfoView.Setting+BetterEducationInfoView"] =
            "BetterEducationInfoviewSettings",
        ["RoadRailSpeeds.SpeedLimitsSetting+RoadRailSpeeds"] = "AdjustAllSpeedLimitsSettings",
        ["CustomLandParcel.CustomLandParcelSettings+CustomLandParcel"] = "CustomLandParcelSettings",
        ["EmergencyPriority.EmergencyPrioritySetting+EmergencyPriority"] =
            "EmergencyPrioritySettings",
        ["TransitTimetables.TransitTimetablesSetting+TransitTimetables"] =
            "TransitTimetablesSettings",
        ["WholesaleLogistics.WholesaleLogisticsSetting+WholesaleLogistics"] =
            "LocalLogisticsSettings",
        ["StopJaywalking.StopJaywalkingSetting+StopJaywalking"] = "StopJaywalkingSettings",
        ["TownRoadLane.TownRoadLaneSetting+TownRoadLane"] = "TownRoadLaneSettings",
        ["PaulovRentMod.Setting+PaulovRentMod"] = "PaulovsRentModSettings",
        ["PaulovUKEconomy.ModSetting+PaulovUKEconomy"] = "PaulovsUKEconomySettings",
        ["WelfareManagement.WelfareManagementSetting+WelfareManagement"] =
            "RealisticFundingAndManagementSettings",
        ["ServiceSanitationLevy.ServiceSanitationLevySetting+ServiceSanitationLevy"] =
            "ServiceSanitationLevySettings",
        ["PrivateSchoolsHospitals.PrivateSchoolsHospitalsSetting+PrivateSchoolsHospitals"] =
            "UnlockFeesAndPrivatizeSettings",
        ["AutoBulldozer.Setting+AutoBulldozer"] = "AutoBulldozerSettings",
        ["BuildingReviver.Setting+BuildingReviver"] = "BuildingReviverSettings",
        ["CemeteryOverflowManager.Setting+CemeteryOverflowManager"] =
            "CemeteryOverflowManagerSettings",
        ["PrisonOverflowManager.Setting+PrisonOverflowManager"] = "PrisonOverflowManagerSettings",
        ["GridRoadGenerator.Settings.GridRoadGeneratorSettings+GridRoadGenerator"] =
            "GridRoadGeneratorSettings",
        ["SignatureFix.SignatureFixSettings+SignatureFix"] = "SignatureLogisticsSettings",
        ["RemoveAbandonedCars.Settings.Setting+RemoveAbandonedCars"] =
            "RemoveAbandonedCarsSettings",
        ["NaturalRegrowth.Setting+NaturalRegrowth"] = "NaturalRegrowthSettings",
        ["Skyplan.Setting+Skyplan"] = "SkyplanSettings",
        ["ConcurrentBusBoarding.ConcurrentBusBoardingSettings+ConcurrentBusBoarding"] =
            "ConcurrentBusBoardingSettings",
        ["PlopShuffle.PlopShuffleSettings+PlopShuffle"] = "PlopShuffleSettings",
        ["DistrictHeightPolicy.Setting+DistrictHeightPolicy"] = "DistrictHeightPolicySettings",
        ["RoadNameGenerator.Setting+RoadNameGenerator"] = "RoadNameGeneratorSettings",
        ["RealisticTimeAndTraffic.Setting+RealisticTimeAndTraffic"] =
            "RealisticTimeAndTrafficSettings",
        ["RoundaboutMarker.RoundaboutMarkerSettings+RoundaboutMarker"] = "RoundaboutMarkerSettings",
        ["TourismOverhaul.TourismOverhaulSetting+TourismOverhaul"] = "TourismOverhaulSettings",
        ["AreaBulldozer.Setting+AreaBulldozer"] = "AreaBulldozerSettings",
        [
            "Kobbyist.ProgressionControls.KobbyistProgressionControlsSettings+Kobbyist.ProgressionControls"
        ] = "ProgressionControlsSettings",
        ["Planboard.Settings+Planboard"] = "PlanboardSettings",
        ["RealWeatherSync.Settings.RealWeatherSettings+RealWeatherSync"] =
            "RealWeatherSyncSettings",
        ["CSII_Realistic_Alignment.Setting+CSII_Realistic_Alignment"] =
            "RealisticAlignmentSettings",
        ["Copaste.CopasteSettings+Copaste"] = "CopasteSettings",
        ["DistrictGroups.Setting+DistrictGroups"] = "DistrictGroupsSettings",
        ["NoSpeedLimitMarkings.Setting+NoSpeedLimitMarkings"] = "NoSpeedLimitMarkingDecalsSettings",
        ["ParkingControl.PCSettings+ParkingControl"] = "ParkingControlSettings",
        ["RouteFilter.Setting+RouteFilter"] = "RouteFilterSettings",
        ["ScorchedEarth.ScorchedEarthSettings+ScorchedEarth"] = "ScorchedEarthSettings",
        ["CrashRepair.Setting+CrashRepair"] = "CrashRepairSettings",
        ["DedicatedCargoFacilities.Setting+DedicatedCargoFacilities"] =
            "DedicatedCargoFacilitiesSettings",
        ["HistoricalTool.Setting+HistoricalTool"] = "HistoricalToolSettings",
        ["RoadRule.Settings+RoadRule"] = "RoadRuleSettings",
        ["BitulaMod.Setting+BitulaMod"] = "BitulaModSettings",
        ["TaxiTraffic.TaxiSettings+TaxiTraffic"] = "TaxiTrafficSettings",
        ["Seety.Settings.SeetySettings+Seety"] = "SeetySettings",
        ["BulldozerMarquee.Settings+BulldozerMarquee"] = "BulldozerMarqueeSettings",
        ["DimThatHighlight.Settings+DimThatHighlight"] = "DimThatHighlightSettings",
        ["Cs2AutoTranslator.TranslatorSetting+Cs2AutoTranslator"] = "BridgeTheLanguageGapSettings",
        ["SkylinesMaps.ModSettings+SkylinesMaps"] = "SkylinesMapsSettings",
        ["RailwaySignals.Setting+RailwaySignals"] = "RailwaySignalsSettings",
        ["AutoNighttimeLightExtension.Setting+AutoNighttimeLightExtension"] =
            "AutoNightLODExtenderSettings",
        ["CityMonitor.Setting+CityMonitor"] = "CityMonitorSettings",
        ["FirstMapPopup.PopupSettings+FirstMapPopup"] = "NoMoreSignsSettings",
    };

    public static bool IsValid(string key) => ValidKeys.Contains(key);

    public static string GetClassName(string key) =>
        ClassNames.TryGetValue(key, out var className) ? className : null;
}
